### PR TITLE
fix: depends on platform go middleware

### PR DESCRIPTION
**Pull request by avisiedo**
This change update code to depends on platform-go-middleware and update the tests to fit the change.

This remove the dependency on `github.com/redhatinsights/module-update-router v0.0.0-20220708181923-3d8d459361dd` which was evoking a dependency on a dead repository: https://github.com/mitchellh/osext

Additionally add the leverage of `go.openly.dev/pointy v1.3.0` removing the need of current utils.go.

Credits on @cryptomilk who detected the dead repository.
Credits on @subpop who advised about the main change.

### CODE REVIEW

**Review by subpop — CHANGES_REQUESTED** [review]
I like this overall. The switch to `platform-go-middlewares` is less complicated than I guessed it would be. However, could you move the test refactoring into a second/follow-up PR? I think the changes are nice, but not strictly related to this PR. It would help to keep the overall complexity of this PR lower.

**Comment by avisiedo** [comment]
thanks for the review; not sure if what I have made is what you mean; I have created a second PR (#11 ) on top of this with the test refactor, and I have rebased removing the changes related with the tests; so it is divided, but that make the pipeline to fail for this PR; I have tried to do the changes without adding the `pointy` library, but that is still a complex change. Happy to know if I am missing something.

**Comment by subpop** [comment]
Hm. You're right. I seem to have made things more confusing. Sorry about that! It looks like now #11 contains everything
#2 does, but split into 4 commits, is that correct? I certainly don't want failing tests, so maybe those 4 commits on #11 are the best way to move forwards with this at this point?

**Comment by avisiedo** [comment]
no worries mate, thanks for your time; I agree about #11 :+1:   Yea it has 4 commits; if you prefer to squash the 4 commits in only one, let me know; I am happy about that, I split in 4 commits as not sure what was preferred (and to squash commits we are always on time :slightly_smiling_face: ). About #11 I continue comments there (squash or not squash).

**Pull request closed without merging**
